- hosts: all
  sudo: yes

  pre_tasks:
    - name: Install dependencies
      yum: "name={{ item }} state=installed"
      with_items:
        - libselinux-python
        - unzip
        - wget

  vars:
#    java_packages:
#      - java-1.8.0-openjdk
    GOCD_GO_VERSION: 15.2.0-2248
    GOCD_SCM_GIT: true
    GOCD_ADMIN_EMAIL: jenscobie@gmail.com

  roles:
    - { role: tpbrown.gocd, tags: [ 'server' ] }
#    - geerlingguy.java

  tasks:
      - { include: tasks/main.yml }